version: '3'
services:
  nginx:
    image: "thijsferyn/nginx:primary"
    container_name: sflive-nginx
    hostname: nginx
    volumes:
    -  ./:/var/www/html
    ports:
     - "8080:80"  
    depends_on:
      - "php"
  nginx2:
    image: "thijsferyn/nginx:secondary"
    container_name: sflive-nginx2
    hostname: nginx2
    volumes:
    -  ./:/var/www/html
    ports:
     - "8081:80"
    depends_on:
      - "php2"
  php:
    image: "thijsferyn/php:primary"
    restart: always
    container_name: sflive-php
    hostname: php
    volumes:
    -  ./:/var/www/html
    ports:
     - "9000:9000"
  php2:
    image: "thijsferyn/php:secondary"
    restart: always
    container_name: sflive-php2
    hostname: php2
    volumes:
    -  ./:/var/www/html
    ports:
     - "9001:9000"
  varnish:
    image: "thijsferyn/varnish:primary"
    container_name: sflive-varnish
    hostname: varnish
    volumes:
      -  ./default.vcl:/etc/varnish/default.vcl
    ports:
     - "80:6081"
    depends_on:
      - "nginx"
      - "nginx2"